[[TVMFFI]]
arch = "aarch64"
git-tree-sha1 = "c87841bbfa82fe2cd97dd5f1e62a9b0b7b989387"
os = "macos"

    [[TVMFFI.download]]
    sha256 = "532854ad725552b9594380d1640ef778334b0aeb3863e7f4ab5aa27280af43d6"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.aarch64-apple-darwin.tar.gz"
[[TVMFFI]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e5019aabad15a25525c44d13929865565ee5c68"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "dc640f8213bc356733252fd72f192b9c98cd664416cc9fce5411671a8fb71902"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.aarch64-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ff163589db405c01f2873148c0894a079d49cf3"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "053f7ec3648257716bcabf3598f3343118608f7673306d242852714b56bfd892"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.aarch64-linux-musl-cxx11.tar.gz"
[[TVMFFI]]
arch = "aarch64"
git-tree-sha1 = "01e5af2a19ecf755113ffbf38163896e19a10472"
os = "freebsd"

    [[TVMFFI.download]]
    sha256 = "5c5a010fe2b5884fcf230accf1ac0d4f48b237a7aada89ac3fb966b170603a99"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.aarch64-unknown-freebsd.tar.gz"
[[TVMFFI]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "644cabeb1731818739b2300d8fac43673b585719"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "159a659b66c1ea3b42dbe11049add15d5244047fd694e7ff207c6f31539c67aa"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0a453faf11eab6c1d6c0fef06e5168939b58ee0"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "8afc6b20ae04aceba52dcf4d9707e3caf0202dbcf2612e7423d8db9c5443fdb2"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eae29238bf033a1b329b434a3167cf9a62214349"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "6d51ec7bb6bbe1e76d906d68e91730c1e2ca28c963ddbcdcf82e69ff4bffc5b1"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3774abd6455de94441e04bec34e4e2ec9c98dce8"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "e1b0221b3a3750ff96704437ec7c204f2392500a1a7f62f24ae60e6e7810e5f6"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c0cde82cbca3130377c9a4acdbe1a359b298147"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "a1a35e052f35f96a0519344480811bbca0898e43ce422e201359553149917aff"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.i686-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43f6eb00925415bdbc5e0894800855d3aeae49b4"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "c9746a23ac8b8ca8ac745cd3b2f0172cdd269782cccc0d5269fa23aaa80d84b9"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.i686-linux-musl-cxx11.tar.gz"
[[TVMFFI]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e5bb50c945a3079f174959057b3f3aff0eb3f9d"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "5fc36d22ab82f856b17260ddbef1ada5ef2092ba1b91e026e83f4a40be2f46e3"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "180f89d0bacdc7558769aec73f42855b066a6ed2"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "b0eab49f0007fd2f46def1ceabd9b44481278f3cac32b527b4458f25a6c5acef"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.riscv64-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "x86_64"
git-tree-sha1 = "5dc274c55e7215fc766cb864f7aea385a4a98a69"
os = "macos"

    [[TVMFFI.download]]
    sha256 = "231e504191f63528bf5a3ea024cbe951ca49e842e68583b5eac94a1fa6389ded"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.x86_64-apple-darwin.tar.gz"
[[TVMFFI]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a7c5f4fb010568ada531480982fe3e66bbe613f"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "2c3a9bdc27bd3f2b4df1a773f134640e0e6df961c9cc917483c80ce0279d0a60"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.x86_64-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76b1d752cc569173d2f897fd84cb17a16b021d61"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "873fa3517a344846c8522ee3df806b981a318958d6c55344b4d7cbe6ff508c3c"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.x86_64-linux-musl-cxx11.tar.gz"
[[TVMFFI]]
arch = "x86_64"
git-tree-sha1 = "12fe99693659ffa6d8beb9d304cc96daa3db06d2"
os = "freebsd"

    [[TVMFFI.download]]
    sha256 = "b57dbd952cf4f3f781e313faba5e6507d55a21afa356d7b69e33e2631c55698c"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.5+0/TVMFFI.v0.1.5.x86_64-unknown-freebsd.tar.gz"
