[[TVMFFI]]
arch = "aarch64"
git-tree-sha1 = "91e4e050c6c6480adb5fc25b9959b89326e0921a"
os = "macos"

    [[TVMFFI.download]]
    sha256 = "663ca42523d2651f08f9a4cfc40b3da642d2a507a03164502c97065f5dd0f68a"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.aarch64-apple-darwin.tar.gz"
[[TVMFFI]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2521bc45f9d7120f00bc9fec266c176d6987ec9a"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "848edbf73ace5d93e6a6e6f83354d54d7fb9f3fb19b2001f8f695b8902a311d1"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.aarch64-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de8c671026be7ee489c80ffceb5556a8e279bcaf"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "ae938dfa6c00dba6769eb35b2ba1d806c5e0e6c4f694ce0d8c6924ad1e31f210"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.aarch64-linux-musl-cxx11.tar.gz"
[[TVMFFI]]
arch = "aarch64"
git-tree-sha1 = "5ad668b9d51c3d6ebd2e96a9c8081d98f6d33a6c"
os = "freebsd"

    [[TVMFFI.download]]
    sha256 = "d9d5d80852541daf525e2faeff9ff20e44f6506f3deff24b7b5e31cb544a7933"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.aarch64-unknown-freebsd.tar.gz"
[[TVMFFI]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65b23cc26596dd57127c2738b621b1d97daa808b"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "740ff63a0016cad6b9eb9c49b18004b09c6d4e24421503b7183998584aeb5bfe"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e97a82379e125942b6cf5e8a3fed748093f0548"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "f2221b58d462e2c2f755d8b7983421fba4d9de6fb1836d69de5e0c8733b230ad"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75d1a3fe719fea6edb470f4e985049800a24d219"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "f5546b0ba00e78ede61017f1b51a95e958c239fa0acb5a02de1c5397d519fb99"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "728af6606b3be6a8de043cbe3e0f87a67501df8f"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "a8cc9046ad7c752d3398bd5606f9f9d62d3145125168d8a9ade99fa945d3faf0"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cab076ed46cd887438f8e89b209b38ca907e420e"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "24c9347ffc7b0c9f99336cf7f7746a69642d21561bc7fa96b419ff73e2b44640"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.i686-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "835cb149408dab7ab6b8d9247e737cc676ea4b53"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "3051ae1de8773e8582375f1f2b7307fd8d990de872948c6e28cc1d8fba217aea"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.i686-linux-musl-cxx11.tar.gz"
[[TVMFFI]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4054006349922ed90c28f754ee673dfd2803bce"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "dc05b2d2dd88e2aeb2447a20e480e91075465f6eb88689babbbb881409d983c2"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d086d37023daa70b5dfdfb3ece251541ec1dc31"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "6426fe4813d3ef73b0cf91b4b1cf92093f740c1c4ac481b49c3c99c8e45c7166"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.riscv64-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "x86_64"
git-tree-sha1 = "add0a1a1e6ac24e7b5b4a0d454c18290d830c341"
os = "macos"

    [[TVMFFI.download]]
    sha256 = "7fc936ea10d0f72870704f016e57e939ac0e034ae17484733a8474902996c7cd"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.x86_64-apple-darwin.tar.gz"
[[TVMFFI]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88dc62f00e978649672b0af5c2c4fd3d4c1db136"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "686fcb9b9353b18a288f5c7e0f3bebe602496c310c0a905de3fde1afa5d43bc6"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.x86_64-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7b81e0292afb99783e5ff35f487e5bf2ea6639d"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "51555ef33c1c9f19c9f178bca201b704a8ab6161384ebc6abf0c59ab8d640ce8"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.x86_64-linux-musl-cxx11.tar.gz"
[[TVMFFI]]
arch = "x86_64"
git-tree-sha1 = "3f88d583dae2682e93fd6e2d2093d61d9206c57e"
os = "freebsd"

    [[TVMFFI.download]]
    sha256 = "58c994714ba691a510e59ddbacab2e3d9d6c876237f02f160d5dbf63e674c172"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+1/TVMFFI.v0.1.3.x86_64-unknown-freebsd.tar.gz"
