[[TVMFFI]]
arch = "aarch64"
git-tree-sha1 = "85cdb9971548e855e1502fc1c21c5f5dbf29f29b"
os = "macos"

    [[TVMFFI.download]]
    sha256 = "3e53dfcc0dec0e89bbf52703807022216230abdac7d9697980e4d0e2dd10d3ba"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.aarch64-apple-darwin.tar.gz"
[[TVMFFI]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2271539053a8f6929f40befb09fda72daaf40d6"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "78c031815be461260e289f26c13ef8d7101256da80bc042c6bb4e2bfb9c5fd01"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.aarch64-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da1f43d7538318e898fbb272cca5a0d81c199c81"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "9c731012cd4a9787039f34b4196cadcebd03c683148a93cfbc7e127c81dc425c"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.aarch64-linux-musl-cxx11.tar.gz"
[[TVMFFI]]
arch = "aarch64"
git-tree-sha1 = "8246b98b66ef656e9248d435ef7d638e9350a0c2"
os = "freebsd"

    [[TVMFFI.download]]
    sha256 = "79f775d58ce5fbe01713478d3498757695012041b3708004752242451725d0ca"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.aarch64-unknown-freebsd.tar.gz"
[[TVMFFI]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff0bccd011d9bcfd18b99277da213eeba5867d9f"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "456217006baf8e05237f71da7bb3af3757cd48793d4008db486203f2280c4daf"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db3e3f69294e8e7789cf51982c9f2394802c508e"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "547bdc857dbcc1ac88b1768a57db6a90b566fbff7c2fe6f097536c4f963ff978"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7474ec4f27a96e4d4097bcce65b1ea8294d4a518"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "cf35ce55bbc84fb5fbf0abdf0381fed9c17d0d8b9322b5d19fbf6f214946b2fa"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3180cbe6827a640cc48be4817c2e41e22ee28d27"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "bb8c2453d527b7be3db5850dc00240d15b1b78dfce277e221307b0dc3fb890e5"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[TVMFFI]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "176912f21965853eb38b9d87e0108dc87a3e8cdb"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "861cbb68307079e8accd5c658dbe4c7bd73a6ffde2ccc0f2d315ef6e922a6db0"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.i686-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d585cd3bbb55000fad63b5fdd1b385e47d3c0fe2"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "c1c8f31f019fdb06daf1d19194258d8c4a5c13ff85ab58037aaf8d50ea539912"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.i686-linux-musl-cxx11.tar.gz"
[[TVMFFI]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f188dd73b1a551c9f511a46a30fd8005241900e"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "a07202c7ea97456dfbbbef29f96c7d96dfeda8a848d6d608754fd9e80c394479"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97629468479e965fbb4e2207a02bc67f039e15a6"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "0f0f4a95fec7c964cf06f8d6ad67a3fc65ede70d8640d7c7b66402a52a58191b"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.riscv64-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "x86_64"
git-tree-sha1 = "cb4f0cf0f427d5d4d9bdb19f3201db515e46bbba"
os = "macos"

    [[TVMFFI.download]]
    sha256 = "64ab53972506f114a862ce898295ba7f96d92a5bfa3d6df7ab6406c6e3ef26c9"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.x86_64-apple-darwin.tar.gz"
[[TVMFFI]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c11033ced4f33d18bdd9fc3cde957395159f741"
libc = "glibc"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "26f0dcbdf0aa7fa5802516ac70a2e3ab56ee6786fc7f8f054795a8bb882c54cd"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.x86_64-linux-gnu-cxx11.tar.gz"
[[TVMFFI]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e68714c1e55be527109e99e92fd85b48c84de8c9"
libc = "musl"
os = "linux"

    [[TVMFFI.download]]
    sha256 = "083ae33fec870f82b34e06876a53c9e9ede88c5b3a32e64c267026b2680d5f3e"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.x86_64-linux-musl-cxx11.tar.gz"
[[TVMFFI]]
arch = "x86_64"
git-tree-sha1 = "3a028fa2df182581e8130a6763fcb96e1d2466ef"
os = "freebsd"

    [[TVMFFI.download]]
    sha256 = "bc73af5752e6a0dc5ef438613b764178f98eb330656ee6b7d4fdc54b08eca88a"
    url = "https://github.com/JuliaBinaryWrappers/TVMFFI_jll.jl/releases/download/TVMFFI-v0.1.3+0/TVMFFI.v0.1.3.x86_64-unknown-freebsd.tar.gz"
